/*******************************************************************************************************
* 
* @ Name :ChatterRecordAccess
* @ Purpose :This class is used to proivde the record access through the @mention user name in the chatter for 
Agile Accelarator,Simple PM. Infuture SEG TS and SEG HR Ticketing tools.

* @ Author: Hanu Sanampudi
* @ Test Class Name : ChatterRecordAccessTest
*
*   Date        |  Developer Name                   |  Version      |  Changes
* ======================================================================================================
*   19-03-2019  |  Hanu Sanampudi     				|  1.0          |  Initial Version
*   16-09-2019	|  external.debasmita.rawooth@seg-automotive.com	|  Added method for access via chatter comments
*******************************************************************************************************/
public without sharing class ChatterRecordAccess {
    
    public ChatterRecordAccess(){
        
    }
}